env:
  browser: true
  es2021: true
  mocha: true
extends:
  - standard
parserOptions:
  ecmaVersion: 2020
  sourceType: module
rules:
  comma-dangle: [0]
  indent: [2, tab]
  no-tabs: 0
  object-curly-spacing: [1, never]
  operator-linebreak: [2, after]
  semi: [1, always]
  no-unused-vars: [0]
  no-new-func: [0]
  require-jsdoc: [2, {
    require: {
      FunctionDeclaration: true,
      MethodDefinition: false,
      ClassDeclaration: true,
      ArrowFunctionExpression: false,
      FunctionExpression: false,
    }
  }]
  "space-before-function-paren": [ 2 , "never"]
